name: web_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"
